[package]
name = "zombienet-sdk-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { version = "0.35.0", default-features = false, features = ["native"] }
tokio = "1.35.0"
tracing-subscriber = "0.3.18"
zombienet-sdk = "0.2"
log = "0.4.20"
anyhow = "1.0.82"
